Task 12
n4sh1r0/ls-aqa-school pull request #16
Opened 2024-12-16 16:01 UTC by n4sh1r0

2025-03-03 15:19 UTC, KanatnikovDA requested changes

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
>          click(byXpath("//*[@id=\"content\"]/form/input[@name=\"submit\"][1]"));
Работает и с ' не обязательно использовать "

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
> +        SelenideElement row = $("td.center input[type='checkbox'][id='" + contactId + "']").closest("tr");
Вот тут String.format("td.center input[type='checkbox'][id='%s']", contactId)

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
> +    public void clickSelectContactById(int contactId) {
@Step

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
>      public void selectContact(ContactData contact) {
@Step

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
>          String NumberStr = message.replaceAll("\\D", "");
название переменных с маленькой

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
>      public boolean listIsEmpty() {
Лучше не использовать в названиях просто List. Вариант: contactList

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
>          return !$("tr[name=\"entry\"]").exists();
Как вариант: $$("сами строки").isEmpty();

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
> +        ElementsCollection contacts = $$(By.name("selected[]"));
Можно вынести в переменные класса

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
> +                .$$("td")
findAll() будет более читабелен

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
> +        contact.setId(Integer.valueOf(rows.get(rowNumber).$(byCssSelector("input")).getAttribute("id")));
byCssSelector не нужен

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
> +        System.out.println("HTML строки: " + row.innerHtml());
Служебные вещи оставлять не нужно

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
> +        String lastName = row.$("td:nth-of-type(2)").getText();
find() в место $()

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
> +    @Step("Получаем id первого контакта")
Форматирование ctrl+shift+l

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
> +    public Set<ContactData> getListOfContacts() {
Step

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/GroupHelper.java
> +        // Ищем чекбокс с нужным значением ID
Комментарии только для сложных кусков кода

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/GroupHelper.java
> +    @Step("Получить строку")
Метод возвращает List а не String "Получить строки" аналогично название метода

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/pages/contact/ContactListPage.java
> +    public ContactListPage dropContact(int contactId) {
А чего не реализовал?

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/pages/contact/ContactListPage.java
> +//    public ContactListPage selectFirstContact() {
комменты

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/pages/contact/ContactListPage.java
>          app.getContactHelper()
FYI: Есть класс Wait который позволяет ждать определенное время до какого-то события

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/pages/contact/ContactListPage.java
> +                .getByRow(0);
Magic Numbers  - не понятно откуда взялся 0; int header = 0; или комментарий поясняющий. Еще вариант javaDocs или @Step

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/pages/group/GroupCreationPage.java
>      public GroupCreationPage fillForm(GroupData group) {
Аргумент лишний, ты никак не обрабатываешь его в методе

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/tests/contact/ContactDeleteTest.java
> +        System.out.println(contactsBefore);
лишнее

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/tests/contact/ContactDeleteTest.java
> +                .as("Проверка счеткика количества контактов")
FYI Есть еще метод: withFailMessage(String msg);

.as("Проверка счеткика количества контактов")
.withFailMessage(String.format("Ожидаемое количестов контактов: %s, фактическое %s",resultIndicator, resultIndicator -1))

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/tests/contact/ContactUpdateTest.java
> +
много пробелов

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/tests/group/GroupDeleteTest.java
> +        //Переходим на страницу с группами
Комменты не нужны

2025-03-03 15:19 UTC, KanatnikovDA commented on addressbook-web-tests/pom.xml
> +            <version>3.24.2</version>
Тоже стоит вынести как и аллюр в переменную

2025-03-03 15:19 UTC, KanatnikovDA commented on .idea/compiler.xml
>        <profile name="Maven default annotation processors profile" enabled="true">
Добавь всю папку .idea в gitignore

2025-03-04 11:38 UTC, n4sh1r0 commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/pages/contact/ContactListPage.java
> +    public ContactListPage dropContact(int contactId) {
))

2025-03-12 07:21 UTC, 13nadcatiy commented on addressbook-web-tests/src/test/java/ru/ls/qa/school/addressbook/app/ContactHelper.java
>          click(byXpath("//*[@id=\"content\"]/form/input[@name=\"submit\"][1]"));
поправили

2025-03-12 07:50 UTC, 13nadcatiy requested changes
сократите названия методов в Page и Helper-классах (например getNavigatorHelper() → goTo())

2025-03-12 07:50 UTC, 13nadcatiy commented on addressbook-web-tests/pom.xml
> +            <version>3.24.2</version>
сделано

2025-03-19 14:32 UTC, 13nadcatiy requested changes
Нужно найти места, где используется билдер. по типу ContactData.builder().build();
нужно заполнять полу в самом билдере, а не после создания объекта, через сеттеры

2025-04-02 07:11 UTC, KanatnikovDA approved these changes

2025-04-02 07:23 UTC, 13nadcatiy approved these changes

2025-04-02 07:24 UTC, merged